.TH "AUDIT_GET_CAPCONTID" "26" "Aug 2019" "Red Hat" "Linux Audit API"
.SH NAME
audit_get_capcontid \- Get a program's capability container id value
.SH SYNOPSIS
.B #include <libaudit.h>
.sp
int audit_get_capcontid(pid_t pid);

.SH DESCRIPTION
This function returns the pid task's audit capability container identifier attribute.

.SH "RETURN VALUE"

This function returns the audit capability container identifier value if it is implemented. It will return a \-1 if the audit capability container identifier is unavailable.

.SH "ERRORS"

This function returns \-2 on failure. Additionally, in the event of a real error, errno would be set. The function can set errno based on failures of open, read, or strtoull.

.SH "SEE ALSO"

.BR audit_set_capcontid (3).

.SH AUTHOR
Richard Guy Briggs
