.TH "AUDIT_SET_CAPCONTID" "26" "Aug 2019" "Red Hat" "Linux Audit API"
.SH NAME
audit_set_capcontid \- Set a program's capability container id value
.SH SYNOPSIS
.B #include <libaudit.h>
.sp
int audit_set_capcontid(pid_t pid, uint32_t capcontid);

.SH "DESCRIPTION"

This function sets the pid task's attribute capability container id with the value of capcontid. The capcontid value may only be set by programs with the CAP_AUDIT_CONTROL capability in the initial user namespace or with capcontid. This normally means the root account or root in a container.
.sp
The capcontid value is part of the task structure and is inheritted by child processes within a user namespace. It is used to enable the capability to set container identifier of a child task in a descendent user namespace.  Container orchestrator/engines should set this value only on children it wishes to be able to set audit container identifiers.

.SH "RETURN VALUE"

This function returns 0 on success and non-zero otherwise.

.SH "SEE ALSO"

.BR audit_get_capcontid (3).

.SH AUTHOR
Richard Guy Briggs
