.TH "AUDIT_GET_CONTAINERID" "3" "Feb 2018" "Red Hat" "Linux Audit API"
.SH NAME
audit_get_containerid \- Get a program's container id value
.SH SYNOPSIS
.B #include <libaudit.h>
.sp
uin64_t audit_get_containerid(pid_t pid);

.SH DESCRIPTION
This function returns the pid task's audit container identifier attribute.

.SH "RETURN VALUE"

This function returns the audit container identifier value if it was set. It will return a \-1 if the audit container identifier is unset. However, since uint64_t is an unsigned type, you will see the converted value instead of \-1.

.SH "ERRORS"

This function returns \-2 on failure. Additionally, in the event of a real error, errno would be set. The function can set errno based on failures of open, read, or strtoull.

.SH "SEE ALSO"

.BR audit_set_containerid (3).

.SH AUTHOR
Richard Guy Briggs
